name: fremad
version: 0.0.1
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  angular: 1.0.0
  uuid: ">=0.1.6 <=1.0.0"
dev_dependencies:
  dartmocks: ">= 0.5.0"
  guinness: ">= 0.1.3"
environment:
  sdk: ">=0.8.10 <2.0.0"
transformers:
- angular